title: Wing Kee Winnie Kwok
logo: ![Alt text](https://github.com/wingkeewinniekwok-max/Portfolio/blob/main/Headshot)
description: Aspiring business analyst dedicated to curiosity, problem-solving, and meaningful social impact.
show_downloads: False
theme: jekyll-theme-minimal
