title: "Wing Kee Winnie Kwok"
logo: "https://github.com/wingkeewinniekwok-max/Portfolio/blob/main/Headshot?raw=true"
description: "Aspiring business analyst dedicated to curiosity, problem-solving, and meaningful social impact."
show_downloads: false
theme: jekyll-theme-minimal
