title: Wing Kee Winnie Kwok
logo: ![Alt text](https://github.com/wingkeewinniekwok-max/Portfolio/blob/main/Headshot)
description: Aspiring business analyst driven by curiosity and problem-solving, committed to creating meaningful social impact.
show_downloads: False
theme: jekyll-theme-minimal
